BLESSING_STICKERS = [
    "CAACAgUAAxkBAAMDabGxdbW8rq1Bv97NN_tGo1ji_vsAAqYAA_ThogjHDT_yFUPtCToE",
    "CAACAgUAAxkBAAMFabGxes9XSsy9PGEkRwjEffVXJIcAAqUAA_Thogi50QZFifEwbzoE",
    "CAACAgUAAxkBAAMHabGxfotcjPpgahYq2h2XxYYaRPwAArIAA_Thogi1JtxL9HFx6joE",
    "CAACAgUAAxkBAAMLabGxkkGYQKE1CNA5TZVxsqrnuqIAAnUDAAJGXUlWO92W7ESI96E6BA",
    # Duplicate removed: "CAACAgUAAxkBAAMLabGxkkGYQKE1CNA5TZVxsqrnuqIAAnUDAAJGXUlWO92W7ESI96E6BA"
    "CAACAgUAAxkBAAMPabGxoVGs70-2RjVxZCww4AulnWEAAkgDAAIO71FWPI4_JzimwEU6BA",
    "CAACAgUAAxkBAAMRabGxtx7oZmvfRQRPR0ke-kNjcV8AArYAA_Thogid4-83u7JJljoE",
    "CAACAgUAAxkBAAMTabGxxNl38uRFgpgbuN1mw0_xV_wAAlMAA_ThogitSEgJ8k4X7DoE",
    "CAACAgUAAxkBAAMVabGxyklqswABrxeaif9rKvmuHoLwAAJlAAP04aIIiP_r3RZYapM6BA",
    "CAACAgUAAxkBAAMXabGxzue-bDUPWmHLrAABooUxu4B_AAJnAAP04aIIR9chFYY38oM6BA",
    "CAACAgUAAxkBAAMZabGx12WW__03LLH-hg48PlY-guAAAnAAA_ThoghhiL9l67clEjoE",
    "CAACAgUAAxkBAAMbabGx2dtf2q24SILnHA0slj1LxpkAAnEAA_ThogiG_hrKH0jOAToE",
    "CAACAgUAAxkBAAMdabGx3gXXysf5Dpyr_vUdLE8dXJcAAnQAA_ThoggYDI4eY37hDzoE",
    "CAACAgUAAxkBAAMfabGx4Bt2_1A7mKdEm0PjeKS6r1cAAnUAA_ThogjEwxzi1brQCDoE",
    "CAACAgUAAxkBAAMgabGx5sb7FKIt3hwVlgKP87aW8o8AAn8AA_ThogjSRyh4VdWP2DoE",
    "CAACAgUAAxkBAAMjabGyBhcrZwvo6QjB8p-MY7XmBcAAAjAAA_ThoggYavFCP3FY-ToE",
]

PETTING_STICKER = "CAACAgUAAxkBAAMNabGxmxA5TPsUBJTJ-3MBmSSuw7MAAlsFAAKTQ1BW67k5vg5b0Hs6BA"
